# Generated by Django 4.0.6 on 2022-07-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='actulizacion',
            new_name='actualizacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='actulizacion',
            new_name='actualizacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
